### ISSUE TITLE
Usage license for estimote-specs scripts 

### ISSUE THREAD

**Issue by rafasimionato** [Estimote/estimote-specs#3]
Hi dear support team,

I am using thses scripts to decode Location Beacons telemetry packets. I have had to modify original code a little to collect data into my app structure. Now I am looking for the license and copyright of this release so I can attend to any required obligation before publishing my solution.

Could you please make this information available for this GitHub project ?

ps: request also sent to forum at https://forums.estimote.com/t/usage-license-for-estimote-specs-scripts/7459.

**Comment by rafasimionato** [comment]
Just found it at https://github.com/Estimote/estimote-specs/blob/master/package.json. I would sugguest make it clear giving this information at README.md.

**Comment by heypiotr** [comment]
Good point, thanks! I've added the LICENSE.md file and clarified the scope (MIT for the example code, full rights reserved for the advertising protocols themselves).
