### ISSUE TITLE
Magnetic Field values

### ISSUE THREAD

**Issue by xiaomi007** [Estimote/estimote-specs#4]
Hello,

The [magnetic Field](https://github.com/Estimote/estimote-specs/blob/master/estimote-telemetry.js#L153-L163) indicates a normalization on the range `[-1:1)`.

The issue here is that `int8 * 2 / 128` gives a range of `[-2: 2)` (from `-128*2/128` to `127*2/128` ).

Should the formula be `int8 / 128` instead of `int8 * 2 / 128` to get the `[-1:1)` normalization ?

Thank you

**Comment by heypiotr** [comment]
You're of course right, thanks!
