### ISSUE TITLE
Nearables packet documentation incomplete; Battery levels; Byte 12?

### ISSUE THREAD

**Issue by jliphard** [Estimote/estimote-specs#5]
Hi - Thanks for releasing the nearables packet documentation. According to the Estimote web site, the custom nearables data packet contains battery information, but there is no indication of this in the released packet specs. Also - the packet specs do not specify the content of byte 12 - the DeviceID terminates at byte 11 (inclusive) and the Temperature field starts at byte 14. Could you shed some light on the disconnect between the Estimate web site and the released nearables packet spec, and what is stored in bytes 12 and 13 - it's not the battery level, since the value seems to be fixed at "0401" or "0485"? That would leave byte 22 for the battery level? Thanks so much!

**Comment by jliphard** [comment]
I found some more info [here](https://github.com/sandeepmistry/node-bleacon/blob/master/estimote-sticker/estimote-sticker.js). The upshot is the voltage is stored in bytes 14 and 15, with 15 doing double duty to encode movement state (in bit 7), and 1/2 of byte 14 encode part of the temperature. The code below gives me reasonable numbers for the voltage (around 3 Volts) if I change manufacturerData.readUInt8(15) << 8 to manufacturerData.readUInt8(15) << 4. Note that there is still one issue - both bits 8 and 7 of byte 15 need to be == 0 for the voltage to be correct. I have not been able to find documentation about the meaning of bit 8 of byte 15.

```
var batteryVoltage = 0;

if ((manufacturerData.readUInt8(15) & 0x80) === 0) {
      var rawBatteryLevel = (manufacturerData.readUInt8(15) << 8) + ((manufacturerData.readUInt8(14) >> 4) & 0x3ff);
      batteryVoltage = 3.6 * rawBatteryLevel / 1023.0;
}
```

So here is my final iOS swift code:
```
//Packet 14
indxBeg = packet.index(packet.startIndex, offsetBy: 28)
indxEnd = packet.index(packet.startIndex, offsetBy: 30)
let b14 = UInt8(packet[indxBeg..<indxEnd], radix: 16)!

//packet 15
indxBeg = packet.index(packet.startIndex, offsetBy: 30)
indxEnd = packet.index(packet.startIndex, offsetBy: 32)
let b15 = UInt8(packet[indxBeg..<indxEnd], radix: 16)!
                
let rawBatteryLevel: UInt16 = (UInt16(b15) << 4) + (UInt16(b14 >> 4) & 0x3ff);
let batteryVoltage = 3.6 * Double(rawBatteryLevel) / 1023.0;
                
// voltage not correct during movement
 if ( ((b15 & 0x80) == 0) && ((b15 & 0x40) == 0) ) {
         print("Voltage: \(batteryVoltage)")
}
```

**Comment by heypiotr** [comment]
Thanks for your comments! The things I didn't include in the spec ... honestly, I just thought they're not that useful and important (: 

I now added code for parsing the battery voltage, and added a comment that bytes 11 and 12 are just hardware and firmware info.
