### ISSUE TITLE
Pressure and ambient light level number too high

### ISSUE THREAD

**Issue by windtalkerlv** [Estimote/estimote-specs#6]
When parsing the telemetry data, it gives output `ambientLightLevel: 353894.39999999997` and `  pressure: 16777215.99609375`

**Comment by heypiotr** [comment]
The values are actually parsed correctly—these weird numbers is what the beacon reports if the sensor is missing. For example, only select Location Beacons have the pressure and ambient light sensors. It'd probably be better if the beacon reported zeroes in such cases, but that's not currently the case.
